apiVersion: v1
kind: PersistentVolume
metadata:
  name: pouw-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/pouw-data"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pouw-pv-claim
spec:
  storageClassName: manual 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pouw-bucket-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/pouw-bucket"
    
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pouw-bucket-pv-claim
spec:
  storageClassName: manual 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
